### ISSUE TITLE
How to send custom message with stages and attach html report

### ISSUE THREAD

**Issue by HernanMinted** [YOU54F/cypress-plugins#1034]
@YOU54F  I have a question about, how I can create a custom message and if is possible add at what stage of my ci pipeline is running this and who triggered it (idk if with Gitlab this is possible). as for I have is 
 "slack-report": "npx cypress-slack-reporter --report-dir './cypress/report/output.json' --custom-url './final-report/output.html' --ci-provider custom --vcs-provider none --verbose true ".

what I tried to do with custom-url is to get that .html as a clickable attachment in the message to get redirected to that but my slack message is the following:

![image](https://user-images.githubusercontent.com/82839075/121252111-062d5200-c87e-11eb-816f-994d3bec712f.png)

**Comment by luisaangelicag** [comment]
@YOU54F Encountering the same issue. The custom url merges to the screenshot directory for the Test Report attachment/button

`npx cypress-slack-reporter --report-dir cypress/reports/mochareports --ci-provider custom --custom-url ~/cypress/reports/mochareports/report.html `

![image](https://user-images.githubusercontent.com/63622377/126657739-3fb0b1d0-930c-4988-a925-e4beea79a0d4.png)

**Comment by YOU54F** [comment]
Custom url is the basepath for somewhere you are sorting artefacts if not
on circleci iirc

**Comment by YOU54F** [comment]
See here for info

https://github.com/YOU54F/cypress-slack-reporter/issues/497#issuecomment-630514390

It would probably be worth adding this into the readme. Would be happy to accept contributions if this works for you 🤘🏽

**Comment by YOU54F** [comment]
@luisaangelicag @HernanMinted ☝🏾 :)

**Comment by luisaangelicag** [comment]
Hi @YOU54F 

checked the issue you linked above though it wasn't able to address my issue. i'm using the file location since i'm running the scripts locally too. will it be possible to use the root directory? from what i'm seeing, the custom-url appends to the screenshots directory

**Comment by YOU54F** [comment]
FYI,

I am going to support sending custom blocks in the new rollout, details to come soon, but it will allow users to send any number of structured (and typed) objects to the message builder, so it should be infinitely customisable

**Comment by HernanMinted** [comment]
@luisaangelicag have you been able to fix this issue? may you share what was your path to make it work?

**Comment by YOU54F** [comment]
Just to clarify you cannot provide the `--custom-url` property a relative path from your machine.

![Screenshot 2022-04-29 at 01 46 59](https://user-images.githubusercontent.com/19932401/165869522-b705b9e0-ccb7-4607-b5b4-ec31fdff9b7a.png)

If needs to be a valid web URL.

A link will need to appear like this  in slack to render 

`<http://sometesturl.com/pnggrad16rgb.png|Screenshot:- pnggrad16rgb.png>`

![Screenshot 2022-04-29 at 01 48 18](https://user-images.githubusercontent.com/19932401/165869649-2ef82513-099a-4afc-91c4-1143e922d070.png)


Custom blocks coming soon, you'll be able to add as many of these as you want 👌🏾 

![Screenshot 2022-04-29 at 01 47 38](https://user-images.githubusercontent.com/19932401/165869572-01e8273a-2ccf-45c7-869e-8de131f4fe59.png)

BTW where are you expecting to serve your URL's from? if you provide the uri root for where your report is, you should be fine, with the current version

**Comment by HernanMinted** [comment]
@YOU54F  Ohh I see, so my custom-url is not doing anything haha 🤣 , although my main concern here is that in my case, I can only see a certain amount of only Test passed (if all passed it shows me 141 even tho there are 200+ test that passed) and if it fails then it throws me _Test passed: 0_, what I'm seeing at least for Luisa side is that she have been able to split how many test passed, failed  and the total of tests that run, basically at first this is what I need right now, screenshots and video or html report would be a nice to have.

**Comment by YOU54F** [comment]
I'd need to see your report json file to understand why the numbers are incorrect. 

or take your json and pipe it into jq

```sh
cat cypress/reports/html/index.json | jq .stats
```

```json
{
  "suites": 2,
  "tests": 20,
  "passes": 20,
  "pending": 0,
  "failures": 0,
  "start": "2022-04-28T22:38:51.534Z",
  "end": "2022-04-28T22:39:28.478Z",
  "duration": 24373,
  "testsRegistered": 20,
  "passPercent": 100,
  "pendingPercent": 0,
  "other": 0,
  "hasOther": false,
  "skipped": 0,
  "hasSkipped": false
}
```

They are extracted here

https://github.com/YOU54F/cypress-plugins/blob/c4b4a29d7a40fc9618b12f569184be64b43fb80f/src/slack/slack-alert.ts#L536-L550

and built into the message here

https://github.com/YOU54F/cypress-plugins/blob/c4b4a29d7a40fc9618b12f569184be64b43fb80f/src/slack/slack-alert.ts#L381-L444

Also `--report-dir './cypress/report/output.json'` this should be a directory, which is why the flag is called `--report-dir`, drop the `/output.json`

**Comment by HernanMinted** [comment]
Is there a way to add also the skipped test into the report? or are taken as Error for the webhook?
the --custom-url for screenshots, since I'm using gitlab for CI/CD you can access the artifacts but then you have to download them to see them, in this case I would need to put them on a server in order to actually see the link correctly to it right?

**Comment by luisaangelicag** [comment]
@YOU54F not sure if this needs a separate issue ticket, but I've encountered issues viewing the generated HTML report. It's just blank upon clicking the Test Report, but inspecting the page shows that the test report details are there

![image](https://user-images.githubusercontent.com/63622377/179133270-6cd8d04a-7549-4373-a105-c75f21458cab.png)

**Comment by YOU54F** [comment]
The OP issue should hopefully be resolved by a new flag `--useOnlyCustomUrl` along with your custom-url `http://sometesturl.com/`

https://github.com/YOU54F/cypress-plugins/issues/1216
