### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [YOU54F/cypress-plugins#1120]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by ds4940** [comment]
Hi @YOU54F, what's the status of this plugin with cypress 10 ?

**Comment by YOU54F** [comment]
I haven't had time to test it yet unfortunately and haven't had any reports of it not being compatible.

**Comment by samixchoumi** [comment]
It works with Cypress 12.3.0

**Comment by YOU54F** [comment]
nice one @samixchoumi
