### ISSUE TITLE
html report index file as parameter

### ISSUE THREAD

**Issue by huseyin-tumer** [YOU54F/cypress-plugins#1161]
My reports are generating with different name instead of mochawesome.html
I want to define it. Could you please add this?
or
I am using "cypress-mochawesome-reporter" with "cypress-multi-reporters".
I want to send report for "cypress-mochawesome-reporter".

**Comment by YOU54F** [comment]
You set this in cypress-mochawesome-reporter's options

https://github.com/LironEr/cypress-mochawesome-reporter#custom-options

which accepts the following flags
