### ISSUE TITLE
Screenshot links no longer visible in Slack links

### ISSUE THREAD

**Issue by you1anna** [YOU54F/cypress-plugins#1164]
Hi, hope you're well @YOU54F!

Since version 1.5.0, links to failed screenshots no longer appear in the post to Slack. 

This was upgraded from v1.2.1 to v1.5.0

Is there any other info I could provide that would help with debugging? 

<img width="608" alt="Screenshot 2022-10-10 at 10 41 11" src="https://user-images.githubusercontent.com/7108767/194838638-d6bdae30-503f-4dd5-97ef-6101c3cfed14.png">
<img width="483" alt="Screenshot 2022-10-10 at 10 41 21" src="https://user-images.githubusercontent.com/7108767/194838645-35df9c23-5faf-4332-89cf-9bfd0bc7a168.png">

Thanks
Robin

**Comment by YOU54F** [comment]
Hey @you1anna 

sorry I’ve not been manning the fort for a while.

hmm yes I think there was some changes to the way to the url was constructed. Any chance you could set me up a repro?

if not will try to have a look this week.

I started writing code for a new one using a block builder so people could easily add their own elements to the message with a nice little slack builder library.

It was largely done but I am like a magpie and got distracted with another shiny thing :)

code is here if you want to take a look

https://github.com/YOU54F/cypress-plugins/blob/master/cypress-slack-reporter/src/index.ts

**Comment by you1anna** [comment]
Thanks @YOU54F, hope you're well!

Bit tricky to setup a repro atm, can you confirm these are the correct dependencies to have on v1.5.0? The issue is that artefacts are not outputted in the build.

```
    "cypress-multi-reporters": "1.6.1",
    "cypress-slack-reporter": "1.5.0",
    "mocha": "10.1.0",
    "mochawesome": "7.1.3",
    "mochawesome-merge": "4.2.1",
    "mochawesome-report-generator": "6.2.0"
```

In your repo I notice there is also [cypress-mochawesome-reporter"](https://github.com/YOU54F/cypress-plugins/blob/master/cypress-slack-reporter/package.json#L37) should this also be included in my dependencies?

**Comment by you1anna** [comment]
@YOU54F Actually there was an issue with Yum downloading dependencies so this can be closed.

Just fyi there is still the issue of failed tests being reported as green, but think you said that would take more investigation.

<img width="593" alt="Screenshot 2022-11-22 at 11 44 55" src="https://user-images.githubusercontent.com/7108767/203306136-d3d480bb-63af-4c44-8edd-494191d273c8.png">

**Comment by YOU54F** [comment]
Thanks matey, I've marked the other ticket as help wanted

https://github.com/YOU54F/cypress-plugins/issues/995

btw cypress-mochawesome-reporter is a nicer/easier way of generating your reports

https://github.com/LironEr/cypress-mochawesome-reporter

Am all good thank you, been super busy this year with the new job over at Pact but have been loving it!
