### ISSUE TITLE
cypress-multi-reporters: reporterEnabled with a relative path not loading options correctly

### ISSUE THREAD

**Issue by leo-coco** [YOU54F/cypress-plugins#1228]
I have a hard time making the configuration of a reporter correctly taken into account. I use a mono repo. Each app has its own cypress configuration, and the reporter is located in a libs `cypress-lib`

When I run cypress, I can see in the log that SpiraReporter is taken into account, but the options are not.

### Question

Should I use a relative path? 

I tried `@cypress-lib/reporter/SpiraReporter` and `@cypress-lib/src/reporter/SpiraReporter` but got this error `"@cypress-lib/reporter/SpiraReporter" reporter not found
`

How should I rename my options `libsCypressLibSrcReporterSpiraReporterOptions` to be correctly found? 

##### reporter-config.json 

```
{
  "reporterEnabled": [
    "spec",
    "mocha-junit-reporter",
    "../../libs/cypress-lib/src/reporter/SpiraReporter"
  ],
  "libsCypressLibSrcReporterSpiraReporterOptions": {
    "projectId": 5,
    "testSetId": 57,
    "login": "XXXXX",
    "apiKey": "{XXXXXX}",
    "protocol": "https",
    "host": "xxxx.spiraservice.net",
    "vdir": "",
    "mapping": {
      "with a checked task": 4,
      "with a checked task 2": 5
    }
  },
  "mochaJunitReporterReporterOptions": {
    "mochaFile": "cypress/results/results-[hash].xml"
  }
}
```

##### Project structure
- apps
  - app-a
    - reporter-config.json 
  - app-b
    - reporter-config.json
- libs
  - cypress-lib
    - src
      - reporter 
        - SpiraReporter

**Comment by amuresia** [comment]
Hi @leo-coco,

Could you please share your solution? I am facing the same issue where reporter options are not taken into account when I use
```
"reporterEnabled": "../../node_modules/mochawesome, ../../node_modules/mocha-junit-reporter",
```

Thank you!
