### ISSUE TITLE
Cypress slack report not showing skipped tests

### ISSUE THREAD

**Issue by Shubham1406220** [YOU54F/cypress-plugins#1231]
In our cypress tests, few are getting skipped in the mochawesome report it shows the skipped count but when send the notification on slack it doesn't show the skipped test count
![image](https://user-images.githubusercontent.com/76969039/219271352-dafe47b1-a154-4c9f-bfea-a82f63233684.png)

**Comment by YOU54F** [comment]
The code doesn't consider the skipped count, so that is why you don't see it

https://github.com/YOU54F/cypress-plugins/blob/e129d2e164c49918ba2158c09c2332bb32cb628d/cypress-slack-reporter-old/src/slack/slack-alert.ts#L541-L565

**Comment by YOU54F** [comment]
duplicate of #1218
