### ISSUE TITLE
Remove 2.0.1 from cypress-multi-reporters in NPM

### ISSUE THREAD

**Issue by scottpopplewell** [YOU54F/cypress-plugins#1250]
Hi @YOU54F , looks like NPM has v2.0.1 that was published to NPM 5 years ago and the latest release is actually 1.6.4. Would you mind removing 2.0.1? Is that even possible?

https://www.npmjs.com/package/cypress-multi-reporters/v/2.0.1

**Comment by YOU54F** [comment]
Hey bud,

I've just released a 2.x version which trumps that older one

https://www.npmjs.com/package/cypress-multi-reporters/v/2.0.3
