### ISSUE TITLE
"Multiple html reports found & cannot determine filename, omitting html report from message

### ISSUE THREAD

**Issue by ConstantineSF** [YOU54F/cypress-plugins#812]
Hi!
I'm facing with issue that slack message sends empty message in chanell because of those err messages
"Multiple html reports found & cannot determine filename, omitting html report from message
Cannot find test report, so sending build fail message
I have mochareports folder related to package.json
also here is my merge\marge commands - similar to what you suggesting  in previous github issue
"combine-reports": "mochawesome-merge cypress/reports/*.json > mochareports/mochawesome.json",
"generate-report": "marge mochareports/mochawesome.json -f report -o mochareports"
 "create-report": "npm run combine-reports && npm run generate-report"
![image](https://user-images.githubusercontent.com/59865468/95172045-73548900-07bf-11eb-9267-fd1e52af4280.png)
tried to move mochareports folder to cypress folder - didn't get luck with that
any advice? thanks

**Comment by YOU54F** [comment]
Hey @rockthis13 

Could you create an example on https://github.com/YOU54F/cypress-slack-reporter-issue for me please as it will help with investagation. What command are you passing to cypress slack reporter in npm run generate-report?

**Comment by jpalmer-miovision** [comment]
I am having the same issue.  I have a "report.html" file in my mochareports directory, it's the only html file.
I run npx cypress-slack-reporter --ci-provider none
And I get the "multiple html" reports error.

Was there any progress on what happened with this, or how to resolve it?

**Comment by jpalmer-miovision** [comment]
Was able to solve this.  It indeed was a Windows issue.  Globby does not work with backslashes, so had to change:
const reportHTMLFullPath = await globby(path.resolve(reportDir), {
to:
const reportHTMLFullPath = await globby(path.resolve(reportDir).replace(/\\/g, '/'), {

**Comment by meghamanjunath2015** [comment]
I am using mac. I still have the same above issue
<img width="232" alt="report_json_—_cypress" src="https://user-images.githubusercontent.com/13687675/103852559-ef7d9780-5060-11eb-9a7f-2b79c69a9126.png">

**Comment by YOU54F** [comment]
Hey @rockthis13 , @jpalmer-miovision , @meghamanjunath2015, 

Thanks for getting in touch. I've been off the OSS stuff for a while so catching up.

If this will solve for windows, we can determine the platform and the below for windows.

> const reportHTMLFullPath = await globby(path.resolve(reportDir).replace(/\/g, '/'), {

I run on a mac. I think I have may have caused for regressions to existing behaviour, by moving to globby over my previous function. Will do some digging this week 👌🏽

**Comment by YOU54F** [comment]
@jpalmer-miovision the globby issue for windows should be fixed now in `1.1.1-alpha` if you'd like to try

Have added a check for the windows platform which will conditionally escape the backslashes, good catch my friend.

```
    const videos = await globby(
      isWin
        ? path.resolve(process.cwd(), videosDir).replace(/\\/g, "/")
        : path.resolve(process.cwd(), videosDir),
      {
        expandDirectories: {
          files: ["*"],
          extensions: ["mp4"],
        },
      }
    );
```

**Comment by YOU54F** [comment]
so in https://github.com/YOU54F/cypress-slack-reporter/issues/984 it was identified that I provided the same error message if no reports were found or if 2 or more were found! so that would have confused it somewhat.

If I can ask users to try `1.1.8-alpha`

**Comment by YOU54F** [comment]
This may be sorted in v1.2.0, please let me know if not!

**Comment by deepak-quo** [comment]
not working on mac.

**Comment by YOU54F** [comment]
Please raise as new issues, with reproducers if this is still affecting people
