### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Error: GIT_URL not defined!

### ISSUE THREAD

**Issue by shindeanmol3** [YOU54F/cypress-plugins#987]
When we use 

`npx cypress-slack-reporter --ci-provider jenkins`

It is throwing an error as GIT_URL is not defined.

Which GIT_URL we need to mention in command?

**Comment by YOU54F** [comment]
Jenkins should provide it assuming your jenkins job is running from git

**Comment by YOU54F** [comment]
Please raise as new issues, with reproducers if this is still affecting people
